# Generated by Django 4.2.6 on 2023-10-07 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('street', models.CharField(max_length=100, verbose_name='Улица')),
                ('home', models.IntegerField(verbose_name='Номер дома')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('product_model', models.CharField(max_length=255, verbose_name='Модель продукта')),
                ('reliz_date', models.DateField(verbose_name='Дата выхода')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('debt', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Задолженность')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail_chain.contacts', verbose_name='Контакты')),
                ('products', models.ManyToManyField(to='retail_chain.product', verbose_name='Продукты')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='retail_chain.link', verbose_name='Поставщик')),
            ],
        ),
    ]
